[project]
name = "sliver"
version = "0.0.2"
authors = [
  { name="Andy Jackson", email="anj@anjackson.net" },
]
description = "A sliver of a sliver."
readme = "README.md"
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]
dependencies = [
  "pywb@git+https://github.com/webrecorder/pywb#sha1=9de84beead449b1ad61c756e9c031b9e6cc645e6",
  "cdxj-indexer",
  "wacz",
  "shot-scraper"
]

[project.scripts]
sliver = "sliver.cli:cli"

[project.urls]
Homepage = "https://github.com/anjackson/sliver"
Issues = "https://github.com/anjackson/sliver/issues"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true
